"""Prompt assembly for LLM API calls."""

from __future__ import annotations

import re
from typing import Any

from app.prompts.evaluate import build_evaluate_prompt
from app.prompts.skill_gen import build_skill_gen_prompt
from app.prompts.system_role import build_system_prompt

RAG_CONTEXT_PREFIX = (
    "\n\n## Reference Knowledge\n"
    "Use this reference material to improve your output:\n"
    "{rag_context}"
)

# Matches the exact format generated by context_builder.format_skills_list
# Example: "- sk_01: Loop init (Start at 0)"
SKILL_LIST_PATTERN = re.compile(r"- (sk_\d+): (.+?) \((.+?)\)")


def build_skill_gen_messages(
    question_description: str,
    starter_code: str,
    language: str,
    rag_context: str = "",
    already_approved_skills: list[dict[str, str]] | None = None,
) -> tuple[str, str]:
    """Build system and user prompts for Phase 1 (Micro-Skill Generation).

    Args:
        question_description: The assignment prompt text.
        starter_code: The teacher's starter code.
        language: The programming language.
        rag_context: Optional retrieved context from the vector DB.
        already_approved_skills: Optional list of approved skills to exclude.

    Returns:
        A tuple of (system_prompt, user_prompt).
    """
    system_prompt = build_system_prompt()

    user_prompt = build_skill_gen_prompt(
        question_description=question_description,
        starter_code=starter_code,
        language=language,
        already_approved_skills=already_approved_skills,
    )

    if rag_context:
        user_prompt += RAG_CONTEXT_PREFIX.format(rag_context=rag_context)

    return system_prompt, user_prompt


def build_evaluation_messages(context: dict[str, Any]) -> tuple[str, str]:
    """Build system and user prompts for Phase 2 (Student Evaluation).

    Bridges the safe context dictionary from context_builder with the
    strict formatting requirements of the evaluation prompt template.

    Args:
        context: The safe context dictionary from context_builder.

    Returns:
        A tuple of (system_prompt, user_prompt).
    """
    system_prompt = build_system_prompt()

    # The evaluate template requires a list of dicts, but context_builder
    # provides a pre-formatted string for logging/safety. We parse it back.
    raw_skills_list = _parse_skills_from_context(context.get("skills_list", ""))

    user_prompt = build_evaluate_prompt(
        question_description=context["question_description"],
        starter_code=context["starter_code"],
        student_code=context["student_code"],
        test_cases_summary=context["test_cases_summary"],
        approved_skills=raw_skills_list,
        language=context["language"],
    )

    if context.get("rag_context"):
        user_prompt += RAG_CONTEXT_PREFIX.format(rag_context=context["rag_context"])

    return system_prompt, user_prompt


def _parse_skills_from_context(skills_list_str: str) -> list[dict[str, str]]:
    """Convert the formatted skills string back to a list of dicts.

    This reverse-parsing is safe because we strictly control the output
    format of context_builder.format_skills_list.

    Args:
        skills_list_str: The newline-separated string of skills.

    Returns:
        A list of skill dictionaries with 'id', 'name', and 'description'.
    """
    if not skills_list_str or skills_list_str == "No skills provided.":
        return []

    matches = SKILL_LIST_PATTERN.findall(skills_list_str)

    return [
        {
            "id": match[0],
            "name": match[1],
            "description": match[2],
        }
        for match in matches
    ]